CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    document VARCHAR(20) NOT NULL,
    role VARCHAR(30) NOT NULL,
    password VARCHAR(100) NOT NULL,
    photo TEXT,
    completed BOOLEAN DEFAULT FALSE
);